# Generated by Django 3.1.2 on 2021-10-04 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0038_comment_commenter_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feed',
            new_name='feeds',
        ),
    ]
