# Generated by Django 3.1.2 on 2021-10-04 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_auto_20211004_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed',
            old_name='feeds',
            new_name='feed',
        ),
    ]
