# Generated by Django 3.1.2 on 2021-10-04 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0042_auto_20211004_1330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='feed',
            new_name='feeds',
        ),
    ]
