# Generated by Django 3.1.2 on 2021-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0043_auto_20211004_1342'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=99)),
                ('name', models.CharField(max_length=99)),
                ('email', models.CharField(max_length=99)),
                ('phone', models.CharField(max_length=99)),
                ('address', models.CharField(max_length=99)),
                ('university', models.CharField(max_length=99)),
                ('university_id', models.CharField(max_length=99)),
                ('nid', models.CharField(max_length=99)),
                ('status', models.CharField(max_length=19)),
            ],
        ),
    ]
