# Generated by Django 3.1.2 on 2021-10-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0044_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='name',
            field=models.CharField(default='Shariar Kabir', max_length=99),
        ),
    ]
