# Generated by Django 3.1.2 on 2021-10-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0045_feeds_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='category',
            field=models.CharField(default='Medicine Specialist', max_length=99),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='status',
            field=models.CharField(max_length=99),
        ),
    ]
